# Generated by Django 5.2.1 on 2025-06-07 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
                ("conf_password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="BookSlot",
            fields=[
                ("client_id", models.AutoField(primary_key=True, serialize=False)),
                ("client_name", models.CharField(max_length=100)),
                ("client_email", models.EmailField(max_length=254)),
                ("slottype", models.CharField(max_length=100)),
                ("trainee", models.CharField(blank=True, max_length=100, null=True)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="fitnee.register",
                    ),
                ),
            ],
        ),
    ]
