# Generated by Django 5.2.1 on 2025-06-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitnee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookslot",
            name="trainee",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
